language: bash
services: docker

env:
  global:
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.7 FULL_VERSION=7.7.9
    - MAJOR_VERSION=7.8 FULL_VERSION=7.8.5
    - LATEST=1 MAJOR_VERSION=7.9 FULL_VERSION=7.9.10
    - LATEST=1 MAJOR_VERSION=7.9 FULL_VERSION=7.9.10 EDITION=edge

before_script:
  - cd "$MAJOR_VERSION"
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - travis_retry docker build --build-arg IGNITION_EDITION=${EDITION:-full} -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin
  - if [ -z ${PRERELEASE+x} ]; then docker tag "$FULL_IMAGE" "$MAJOR_IMAGE"; fi
  - if [ ! -z ${LATEST+x} ]; then docker tag "$MAJOR_IMAGE" "$LATEST_IMAGE"; fi

deploy:
  provider: script
  script: docker push "$FULL_IMAGE" && if [ -z ${PRERELEASE+x} ]; then docker push "$MAJOR_IMAGE"; fi && if [ ! -z ${LATEST+x} ]; then docker push "$LATEST_IMAGE"; fi
  on:
    branch: master
