language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.7 FULL_VERSION=7.7.10 DOWNLOAD_URL=https://files.inductiveautomation.com/release/build7.7.10/2018112117/ignition-7.7.10-linux-x64-installer.run DOWNLOAD_MD5=1a22a4e482197f4a317d8455cd54b4a1
    - MAJOR_VERSION=7.8 FULL_VERSION=7.8.5 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.8.5/20161208-1312/Ignition-7.8.5-linux-x64-installer.run DOWNLOAD_MD5=dffb12fb1df320fb569ca38bcd71b347
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.13 DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build7.9.13/20191209-1521/zip-installers/Ignition-7.9.13-linux-x64-installer.run DOWNLOAD_MD5=1d33de6f71790bd850938e8578b44e41
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.13 EDITION=edge DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build7.9.13/20191209-1521/zip-installers/Ignition-7.9.13-linux-x64-installer.run DOWNLOAD_MD5=1d33de6f71790bd850938e8578b44e41
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.8 DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/8.0.8/20200211-1129/Ignition-linux-64-8.0.8.zip DOWNLOAD_SHA256=623fd6e978ebf5f145521a15f029fb5437ff557b047adedd875f84eab197b558
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.8 EDITION=edge DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/8.0.8/20200211-1129/Ignition-Edge-linux-64-8.0.8.zip DOWNLOAD_SHA256=9127492dfb8caeafd0cc6c636d21a85762000a2204a854001780979b9c5d9efa

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - cd "$MAJOR_VERSION"
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - travis_retry docker build --build-arg IGNITION_EDITION=${EDITION:-full} ${DOWNLOAD_URL:+--build-arg IGNITION_DOWNLOAD_URL=${DOWNLOAD_URL}} ${DOWNLOAD_MD5:+--build-arg IGNITION_DOWNLOAD_MD5=${DOWNLOAD_MD5}} ${DOWNLOAD_SHA256:+--build-arg IGNITION_DOWNLOAD_SHA256=${DOWNLOAD_SHA256}} -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin
  - if [ -z ${PRERELEASE+x} ]; then docker tag "$FULL_IMAGE" "$MAJOR_IMAGE"; fi
  - if [ ! -z ${LATEST+x} ]; then docker tag "$MAJOR_IMAGE" "$LATEST_IMAGE"; fi

deploy:
  provider: script
  script: docker push "$FULL_IMAGE" && if [ -z ${PRERELEASE+x} ]; then docker push "$MAJOR_IMAGE"; fi && if [ ! -z ${LATEST+x} ]; then docker push "$LATEST_IMAGE"; fi
  on:
    branch: master
