language: bash
services: docker

env:
  global:
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.7 FULL_VERSION=7.7.9 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/build7.7.9/2018060503/ignition-7.7.9-linux-x64-installer.run DOWNLOAD_MD5=a7a0736dc9ee2e1f25b8ab72d389f9af
    - MAJOR_VERSION=7.8 FULL_VERSION=7.8.5 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.8.5/20161208-1312/Ignition-7.8.5-linux-x64-installer.run DOWNLOAD_MD5=dffb12fb1df320fb569ca38bcd71b347
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.10 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.9.10/20181128-1303/zip-installers/Ignition-7.9.10-linux-x64-installer.run DOWNLOAD_MD5=414dae5fb8ccfa94e74cd11730c45aeb
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.10 EDITION=edge DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.9.10/20181128-1303/zip-installers/Ignition-7.9.10-linux-x64-installer.run DOWNLOAD_MD5=414dae5fb8ccfa94e74cd11730c45aeb
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.1 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build8.0.1/20190507-0808/Ignition-linux-64-8.0.1.zip DOWNLOAD_SHA256=4c292a375b39676c0eb1b9bd83d0f20b69589e6a132a5e48761db8df1a1a4c23
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.1 EDITION=edge DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build8.0.1/20190507-0808/Ignition-Edge-linux-64-8.0.1.zip DOWNLOAD_SHA256=66234188d4cf826be65efb00ac09c1056635afd5b70f7ffd8d80f26bb058892e

before_script:
  - cd "$MAJOR_VERSION"
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - travis_retry docker build --build-arg IGNITION_EDITION=${EDITION:-full} ${DOWNLOAD_URL:+--build-arg IGNITION_DOWNLOAD_URL=${DOWNLOAD_URL}} ${DOWNLOAD_MD5:+--build-arg IGNITION_DOWNLOAD_MD5=${DOWNLOAD_MD5}} ${DOWNLOAD_SHA256:+--build-arg IGNITION_DOWNLOAD_SHA256=${DOWNLOAD_SHA256}} -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin
  - if [ -z ${PRERELEASE+x} ]; then docker tag "$FULL_IMAGE" "$MAJOR_IMAGE"; fi
  - if [ ! -z ${LATEST+x} ]; then docker tag "$MAJOR_IMAGE" "$LATEST_IMAGE"; fi

deploy:
  provider: script
  script: docker push "$FULL_IMAGE" && if [ -z ${PRERELEASE+x} ]; then docker push "$MAJOR_IMAGE"; fi && if [ ! -z ${LATEST+x} ]; then docker push "$LATEST_IMAGE"; fi
  on:
    branch: master
