language: bash
services: docker

env:
  global:
    - DOWNLOAD_URL="http://files.inductiveautomation.com/release/ia/build7.9.8/20180607-1450/Ignition-7.9.8-linux-x64-installer.run"
    - DOWNLOAD_MD5="ffbbf12b3080d8b9d74622fb87c22ca0"
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.8
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.8 EDITION=edge

before_script:
  - cd "$MAJOR_VERSION"
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - travis_retry docker build --build-arg IGNITION_EDITION=${EDITION:-full} --build-arg IGNITION_VERSION=$FULL_VERSION --build-arg IGNITION_DOWNLOAD_URL=$DOWNLOAD_URL --build-arg IGNITION_DOWNLOAD_MD5=$DOWNLOAD_MD5 -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin
  - docker tag "$FULL_IMAGE" "$MAJOR_IMAGE"
  - docker tag "$MAJOR_IMAGE" "$LATEST_IMAGE"

deploy:
  provider: script
  script: docker push "$FULL_IMAGE" && docker push "$MAJOR_IMAGE" && docker push "$LATEST_IMAGE"
  on:
    branch: master