language: bash
services: docker

env:
  global:
    - IMAGE_NAME=kcollins/ignition
  matrix:
    - MAJOR_VERSION=7.7 FULL_VERSION=7.7.10 DOWNLOAD_URL=https://files.inductiveautomation.com/release/build7.7.10/2018112117/ignition-7.7.10-linux-x64-installer.run DOWNLOAD_MD5=1a22a4e482197f4a317d8455cd54b4a1
    - MAJOR_VERSION=7.8 FULL_VERSION=7.8.5 DOWNLOAD_URL=https://s3.amazonaws.com/files.inductiveautomation.com/release/ia/build7.8.5/20161208-1312/Ignition-7.8.5-linux-x64-installer.run DOWNLOAD_MD5=dffb12fb1df320fb569ca38bcd71b347
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.12 DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build7.9.12/20190702-1353/zip-installers/Ignition-7.9.12-linux-x64-installer.run DOWNLOAD_MD5=9575810208d4d83b6846a39802223770
    - MAJOR_VERSION=7.9 FULL_VERSION=7.9.12 EDITION=edge DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build7.9.12/20190702-1353/zip-installers/Ignition-7.9.12-linux-x64-installer.run DOWNLOAD_MD5=9575810208d4d83b6846a39802223770
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.3 DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build8.0.3/20190807-1716/Ignition-linux-64-8.0.3.zip DOWNLOAD_SHA256=ed50f813994aa73f67159064f79924289e2c9bfab4ced6057ae676a169e5f910
    - LATEST=1 MAJOR_VERSION=8.0 FULL_VERSION=8.0.3 EDITION=edge DOWNLOAD_URL=https://files.inductiveautomation.com/release/ia/build8.0.3/20190807-1716/Ignition-Edge-linux-64-8.0.3.zip DOWNLOAD_SHA256=d46b088a485f71227705cbe0189e00416dfc84e86119aae227c3e5ffd3751811

before_script:
  - cd "$MAJOR_VERSION"
  # Specify image as "kcollins/ignition:7.9.7" or "kcollins/ignition:7.9.7-edge" if edition is set to edge
  - FULL_IMAGE="$IMAGE_NAME:$FULL_VERSION${EDITION:+-$EDITION}"
  - MAJOR_IMAGE="$IMAGE_NAME:$MAJOR_VERSION${EDITION:+-$EDITION}"
  - LATEST_IMAGE="$IMAGE_NAME:latest${EDITION:+-$EDITION}"

script:
  - travis_retry docker build --build-arg IGNITION_EDITION=${EDITION:-full} ${DOWNLOAD_URL:+--build-arg IGNITION_DOWNLOAD_URL=${DOWNLOAD_URL}} ${DOWNLOAD_MD5:+--build-arg IGNITION_DOWNLOAD_MD5=${DOWNLOAD_MD5}} ${DOWNLOAD_SHA256:+--build-arg IGNITION_DOWNLOAD_SHA256=${DOWNLOAD_SHA256}} -t "$FULL_IMAGE" .

after_script:
  - docker images

before_deploy:
  - echo $HUB_PASSWORD | docker login -u "$HUB_LOGIN" --password-stdin
  - if [ -z ${PRERELEASE+x} ]; then docker tag "$FULL_IMAGE" "$MAJOR_IMAGE"; fi
  - if [ ! -z ${LATEST+x} ]; then docker tag "$MAJOR_IMAGE" "$LATEST_IMAGE"; fi

deploy:
  provider: script
  script: docker push "$FULL_IMAGE" && if [ -z ${PRERELEASE+x} ]; then docker push "$MAJOR_IMAGE"; fi && if [ ! -z ${LATEST+x} ]; then docker push "$LATEST_IMAGE"; fi
  on:
    branch: master
